<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_article-fields',
		'title' => 'Article Fields',
		'fields' => array(
			array(
				'key' => 'field_5b73e5700bbf5',
				'label' => 'Flexible content field',
				'name' => 'flexible_content_field',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'5b73e59450e31' => array(
						'key' => '5b73e59450e31',
						'name' => 'header_text',
						'label' => 'Header Text',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb58f294f',
								'label' => 'Header Text',
								'name' => 'header_text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73eb1af294e' => array(
						'key' => '5b73eb1af294e',
						'name' => 'text_block',
						'label' => 'Text Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb6cf2950',
								'label' => 'Text Block',
								'name' => 'text_block',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73eb18f294d' => array(
						'key' => '5b73eb18f294d',
						'name' => 'code_block',
						'label' => 'Code Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb7ff2951',
								'label' => 'Code Block',
								'name' => 'code_block',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73eb16f294c' => array(
						'key' => '5b73eb16f294c',
						'name' => 'image',
						'label' => 'Image',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb90f2952',
								'label' => 'Image_regular',
								'name' => 'image_regular',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5b9f07b0845b2',
								'label' => 'Image_large',
								'name' => 'image_large',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'large',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5b9f07c3845b3',
								'label' => 'Image_full',
								'name' => 'image_full',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73ec1cdb9d3' => array(
						'key' => '5b73ec1cdb9d3',
						'name' => 'embed',
						'label' => 'Embed',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73ec29db9d4',
								'label' => 'Embed',
								'name' => 'embed',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Module',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_breaker',
		'title' => 'Breaker',
		'fields' => array (
			array (
				'key' => 'field_5b694ad065126',
				'label' => 'Breaker Title',
				'name' => 'breaker_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5b693c5664833',
				'label' => 'Breaker Image',
				'name' => 'breaker_image',
				'type' => 'image',
				'save_format' => 'object',
				'preview_size' => 'full',
				'library' => 'all',
			),
			array (
				'key' => 'field_5b693d3064835',
				'label' => 'Description',
				'name' => 'description',
				'type' => 'wysiwyg',
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 'yes',
			),
			array (
				'key' => 'field_5b693cc464834',
				'label' => 'CTA Link',
				'name' => 'cta_link',
				'type' => 'page_link',
				'post_type' => array (
					0 => 'all',
				),
				'allow_null' => 0,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page',
					'operator' => '==',
					'value' => '3',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
