<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b73df02b2fa0',
		'title' => 'Article Fields',
		'fields' => array(
			array(
				'key' => 'field_5b73e5700bbf5',
				'label' => 'Flexible content field',
				'name' => 'flexible_content_field',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'5b73e59450e31' => array(
						'key' => '5b73e59450e31',
						'name' => 'header_text',
						'label' => 'Header Text',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb58f294f',
								'label' => 'Header Text',
								'name' => 'header_text',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73eb1af294e' => array(
						'key' => '5b73eb1af294e',
						'name' => 'text_block',
						'label' => 'Text Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb6cf2950',
								'label' => 'Text Block',
								'name' => 'text_block',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73eb18f294d' => array(
						'key' => '5b73eb18f294d',
						'name' => 'code_block',
						'label' => 'Code Block',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb7ff2951',
								'label' => 'Code Block',
								'name' => 'code_block',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73eb16f294c' => array(
						'key' => '5b73eb16f294c',
						'name' => 'image',
						'label' => 'Image',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73eb90f2952',
								'label' => 'Image_regular',
								'name' => 'image_regular',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5b9f07b0845b2',
								'label' => 'Image_large',
								'name' => 'image_large',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'large',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5b9f07c3845b3',
								'label' => 'Image_full',
								'name' => 'image_full',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'5b73ec1cdb9d3' => array(
						'key' => '5b73ec1cdb9d3',
						'name' => 'embed',
						'label' => 'Embed',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b73ec29db9d4',
								'label' => 'Embed',
								'name' => 'embed',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Module',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));
	
	endif;